In [1]:
import osmnx as ox
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib
import matplotlib.cm as cm
import matplotlib.pyplot as plt
from stateDict import us_state_abbrev
from operator import eq, contains
from scipy.stats import gaussian_kde
import sys
import logging
import signal
from sklearn.neighbors import KernelDensity
from math import radians, cos, sin, asin, sqrt
import utils
from utils import *
from scipy.spatial import cKDTree
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn import svm

citylist = ['Mountainside,NJ,USA','Springfield,NJ,USA','Morristown,NJ,USA','Westfield,NJ,USA','Plainfield,NJ,USA', 'Summit,NJ,USA', 'South Plainfield,NJ,USA', 'Scotch Plains,NJ,USA', 'Garwood,NJ,USA', 'Kenilworth,NJ,USA']
#citylist = ['Mountainside,NJ,USA']
#load the saved city graphs
graphs = []
for cities in citylist:
    graphs.append(loadGraph(cities))

normfullconnectgraphs = []
for g in range(0,len(graphs)):
    normfullconnectgraphs.append(transformGraphToNormalizedFullyConnected(graphs[g],10))

#print(getActualDistanceDataFrame(normfullconnectgraphs[0]))


dfstart = getNodeDataFrame(normfullconnectgraphs[0])
lat = dfstart['x'].values[:,np.newaxis]
longitude = dfstart['y'].values[:,np.newaxis]
for g in range(1,len(graphs)):
    df = getNodeDataFrame(normfullconnectgraphs[g])
    lat = np.concatenate((lat, df['x'].values[:,np.newaxis]))
    longitude = np.concatenate((longitude, df['y'].values[:,np.newaxis]))

# pos=nx.get_node_attributes(normfullconnectgraphs[1],'pos')
# nx.draw(normfullconnectgraphs[1],pos,hold=None,node_size=10)
# plt.show()

#df = getShortestPathDataFrame(normfullconnectgraphs[1])
#df.to_csv('springfieldshort.csv')

#edgeinfo = pd.DataFrame.from_dict(normfullconnectgraphs[1].edges(data=True))
#edgeinfo.to_csv('springfieldedge.csv')

adj, short, total_length = graphMatricesToAdjandShortestPath(graphs,normfullconnectgraphs)

print(adj[0])
print(short[0])
#create one long vector for X and Y
X = short[0]
Y = adj[0]
for g in range (1,len(graphs)):
    X = np.concatenate((X,short[g]))
    Y = np.concatenate((Y,adj[g]))

#remove parts of cities that aren't connected to the rest of the city
isnan = np.where(np.isnan(X) == True)
X = np.delete(X, isnan[0])[:,np.newaxis]
Y = np.delete(Y, isnan[0])[:,np.newaxis]
print(X.shape)

# greater = np.where(X >= 4)
# X = np.delete(X, greater[0])[:,np.newaxis]
# Y = np.delete(Y, greater[0])[:,np.newaxis]
# print(np.sum(Y))
# print(X.shape)
#clf = linear_model.SGDClassifier()
#clf.fit(X, Y)
#clf = linear_model.LogisticRegression(C=1e5,max_iter=1000)
#clf.fit(X, Y)
# print('score',clf.score(X,Y))

nog,fcg = CreateFullyConnectedGraph(lat,longitude,500,10)



# greater = np.where(fcgsp[:,2] >= 4)
# fcgsp = np.delete(fcgsp, greater[0], axis=0)

# print(fcgsp.shape)
# print(fcgsp)
#predictions = clf.predict(fcgsp[:,2][:,np.newaxis])
#print(np.max(predictions))
# print(predictions)
# print(np.sum(predictions))

#final = np.concatenate((fcgsp,predictions[:,np.newaxis]),axis=1)
#print(final)
#final.view('f8,f8,f8,f8').sort(order=['f3'], axis=0)
# print(final.shape)

#lam = .01
#pij = 1/(1+np.exp(lam*fcgsp[:,2]))

#final = np.concatenate((fcgsp,pij[:,np.newaxis]),axis=1)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


g 0
g 1
g 2
g 3
g 4
g 5
g 6
g 7
g 8
g 9
           OSMID1      OSMID2  Adj
0       105466370   655779329  0.0
1       105438722   655779329  0.0
2       105438722   105466370  0.0
3       105461764   655779329  0.0
4       105461764   105466370  0.0
5       105461764   105438722  0.0
6       105500166   655779329  0.0
7       105500166   105466370  0.0
8       105500166   105438722  0.0
9       105500166   105461764  0.0
10      105506826   655779329  0.0
11      105506826   105466370  0.0
12      105506826   105438722  0.0
13      105506826   105461764  0.0
14      105506826   105500166  0.0
15      105438731   655779329  0.0
16      105438731   105466370  0.0
17      105438731   105438722  1.0
18      105438731   105461764  0.0
19      105438731   105500166  0.0
20      105438731   105506826  0.0
21     2454135818   655779329  0.0
22     2454135818   105466370  0.0
23     2454135818   105438722  0.0
24     2454135818   105461764  0.0
25     2454135818   105500166  0.0
26     24541358

In [2]:
eucliddist = getEuclideanDistanceX(normfullconnectgraphs[0])
print(eucliddist)

         Row  Column      Dist
0        1.0     0.0  0.000000
1        2.0     0.0  0.000000
2        2.0     1.0  0.000000
3        3.0     0.0  0.000000
4        3.0     1.0  0.000000
5        3.0     2.0  0.000000
6        4.0     0.0  0.000000
7        4.0     1.0  0.000000
8        4.0     2.0  0.000000
9        4.0     3.0  0.000000
10       5.0     0.0  0.000000
11       5.0     1.0  0.000000
12       5.0     2.0  0.000000
13       5.0     3.0  0.000000
14       5.0     4.0  0.000000
15       6.0     0.0  0.000000
16       6.0     1.0  0.000000
17       6.0     2.0  0.001092
18       6.0     3.0  0.000000
19       6.0     4.0  0.000000
20       6.0     5.0  0.000000
21       7.0     0.0  0.000000
22       7.0     1.0  0.000000
23       7.0     2.0  0.000000
24       7.0     3.0  0.000000
25       7.0     4.0  0.000000
26       7.0     5.0  0.000000
27       7.0     6.0  0.000000
28       8.0     0.0  0.000000
29       8.0     1.0  0.000000
...      ...     ...       ...
55248  3

In [3]:
result = pd.concat([adj[0], short[0]], axis=1)
print(result)

           OSMID1      OSMID2  Adj    Row  Column  Shortpath
0       105466370   655779329  0.0    1.0     0.0        9.0
1       105438722   655779329  0.0    2.0     0.0        5.0
2       105438722   105466370  0.0    2.0     1.0        7.0
3       105461764   655779329  0.0    3.0     0.0        7.0
4       105461764   105466370  0.0    3.0     1.0       12.0
5       105461764   105438722  0.0    3.0     2.0       11.0
6       105500166   655779329  0.0    4.0     0.0        2.0
7       105500166   105466370  0.0    4.0     1.0       10.0
8       105500166   105438722  0.0    4.0     2.0        6.0
9       105500166   105461764  0.0    4.0     3.0        6.0
10      105506826   655779329  0.0    5.0     0.0        3.0
11      105506826   105466370  0.0    5.0     1.0        8.0
12      105506826   105438722  0.0    5.0     2.0        4.0
13      105506826   105461764  0.0    5.0     3.0        8.0
14      105506826   105500166  0.0    5.0     4.0        3.0
15      105438731   6557

In [4]:
df2 = pd.merge(result, eucliddist, on=['Row','Column'], how='inner')
print(df2)

           OSMID1      OSMID2  Adj    Row  Column  Shortpath      Dist
0       105466370   655779329  0.0    1.0     0.0        9.0  0.000000
1       105438722   655779329  0.0    2.0     0.0        5.0  0.000000
2       105438722   105466370  0.0    2.0     1.0        7.0  0.000000
3       105461764   655779329  0.0    3.0     0.0        7.0  0.000000
4       105461764   105466370  0.0    3.0     1.0       12.0  0.000000
5       105461764   105438722  0.0    3.0     2.0       11.0  0.000000
6       105500166   655779329  0.0    4.0     0.0        2.0  0.000000
7       105500166   105466370  0.0    4.0     1.0       10.0  0.000000
8       105500166   105438722  0.0    4.0     2.0        6.0  0.000000
9       105500166   105461764  0.0    4.0     3.0        6.0  0.000000
10      105506826   655779329  0.0    5.0     0.0        3.0  0.000000
11      105506826   105466370  0.0    5.0     1.0        8.0  0.000000
12      105506826   105438722  0.0    5.0     2.0        4.0  0.000000
13    

In [5]:


#print(eucliddist)
#print(np.min(eucliddist[:,2]))
#print(np.max(eucliddist[:,2]))
# between 0 and 1
#btw = np.where((eucliddist[:,2] > 0) & (eucliddist[:,2] < 1))
#print(eucliddist[btw])
#indexed_dist = eucliddist.set_index(['Row', 'Column'])




mat = df2.as_matrix()
print(mat.shape)
btw = np.where((mat[:,6] > 0) & (mat[:,6] <= 1))
mat = mat[btw]
print(mat.shape)
isnan = np.where(np.isnan(mat[:,5]) == False)
mat = mat[isnan]
print(mat.shape)

(55278, 7)
(1784, 7)
(1784, 7)


In [6]:
X = mat[:,[5,6]]
Y = mat[:,2]
Y[Y>1]=1
print(X)
print(X.shape)
print(Y)
print(Y.shape)
print(np.sum(Y))

[[ 1.          0.00109237]
 [ 1.          0.00239761]
 [ 1.          0.00123263]
 ..., 
 [ 1.          0.00218021]
 [ 1.          0.00283788]
 [ 1.          0.00162242]]
(1784, 2)
[ 1.  0.  0. ...,  0.  1.  1.]
(1784,)
380.0


In [7]:
clf = linear_model.LogisticRegression(C=1e5,max_iter=1000)
clf.fit(X, Y)
print('score',clf.score(X,Y))

test = X[:,:]
print(test)
predictions = clf.predict_proba(test)
print(np.average(predictions[:,1]))
great = np.where(predictions[:,1]>.5)
print(predictions[great])
print(predictions[great].shape)

score 0.827914798206
[[ 1.          0.00109237]
 [ 1.          0.00239761]
 [ 1.          0.00123263]
 ..., 
 [ 1.          0.00218021]
 [ 1.          0.00283788]
 [ 1.          0.00162242]]
0.213008447865
[[ 0.2762971   0.7237029 ]
 [ 0.363524    0.636476  ]
 [ 0.49424522  0.50575478]
 [ 0.40588117  0.59411883]
 [ 0.36632073  0.63367927]
 [ 0.45229503  0.54770497]
 [ 0.48525971  0.51474029]
 [ 0.3705134   0.6294866 ]
 [ 0.43242433  0.56757567]
 [ 0.39301389  0.60698611]
 [ 0.42930016  0.57069984]
 [ 0.35758443  0.64241557]
 [ 0.42315276  0.57684724]
 [ 0.44038972  0.55961028]
 [ 0.40292729  0.59707271]
 [ 0.46530599  0.53469401]
 [ 0.49336711  0.50663289]
 [ 0.38635424  0.61364576]
 [ 0.29549246  0.70450754]
 [ 0.44205267  0.55794733]
 [ 0.3307229   0.6692771 ]
 [ 0.39775957  0.60224043]
 [ 0.44986047  0.55013953]
 [ 0.4182278   0.5817722 ]
 [ 0.40419051  0.59580949]
 [ 0.30663878  0.69336122]
 [ 0.27019504  0.72980496]
 [ 0.47148284  0.52851716]
 [ 0.31297626  0.68702374]
 [ 0.264871

In [13]:
fcgsp = getShortestPathX(fcg)
gcpdist = getEuclideanDistanceX(fcg)
dftest = pd.merge(fcgsp, gcpdist, on=['Row','Column'], how='inner')
print(dftest)

mid = dftest.as_matrix()
print(mid.shape)
btwm = np.where((mid[:,3] > 0) & (mid[:,3] <= 1))
mid = mid[btwm]
print(mid.shape)
isnan = np.where(np.isnan(mid[:,2]) == False)
mid = mid[isnan]
print(mid.shape)




          Row  Column  Shortpath      Dist
0         1.0     0.0        4.0  0.000000
1         2.0     0.0        8.0  0.000000
2         2.0     1.0        4.0  0.000000
3         3.0     0.0        6.0  0.000000
4         3.0     1.0        5.0  0.000000
5         3.0     2.0        8.0  0.000000
6         4.0     0.0        8.0  0.000000
7         4.0     1.0        8.0  0.000000
8         4.0     2.0        7.0  0.000000
9         4.0     3.0       12.0  0.000000
10        5.0     0.0       11.0  0.000000
11        5.0     1.0       12.0  0.000000
12        5.0     2.0       11.0  0.000000
13        5.0     3.0       13.0  0.000000
14        5.0     4.0        5.0  0.000000
15        6.0     0.0       10.0  0.000000
16        6.0     1.0        7.0  0.000000
17        6.0     2.0        5.0  0.000000
18        6.0     3.0        6.0  0.000000
19        6.0     4.0       10.0  0.000000
20        6.0     5.0       10.0  0.000000
21        7.0     0.0        8.0  0.000000
22        7

In [15]:
print(mid)
predictions = clf.predict_proba(mid[:,[2,3]])
print(predictions)

[[  1.50000000e+01   0.00000000e+00   1.00000000e+00   3.26539631e-02]
 [  2.00000000e+01   1.40000000e+01   1.00000000e+00   3.99609561e-01]
 [  2.10000000e+01   1.70000000e+01   1.00000000e+00   1.51525547e-01]
 ..., 
 [  4.99000000e+02   4.56000000e+02   1.00000000e+00   1.74050740e-01]
 [  4.99000000e+02   4.80000000e+02   1.00000000e+00   9.85238636e-02]
 [  4.99000000e+02   4.84000000e+02   1.00000000e+00   3.60378539e-02]]
[[  1.00000000e+000   4.31292832e-020]
 [  1.00000000e+000   2.25034801e-243]
 [  1.00000000e+000   2.01669021e-092]
 ..., 
 [  1.00000000e+000   3.96890679e-106]
 [  1.00000000e+000   3.58695100e-060]
 [  1.00000000e+000   3.76501305e-022]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\base.py:352: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)


In [9]:
r,c = final.shape
#add most likely edge for each node
#for i in range (0,r):
#    iter=0
#    for j in range (0,r):
#        if( nog.has_edge(final[j,0],final[j,1])==False and iter<=0 and nog.number_of_edges(final[j,0])<=1):
#            nog.add_edge(final[j,0],final[j,1], origshortpath=final[j,2])
#            iter+=1
            
iter=0
#add in all remaining edges
for j in range (0,r):
    if( nog.has_edge(final[j,0],final[j,1])==False and iter<=2000 and nog.number_of_edges(final[j,0])<=4):
        #draw edge if random number between 0 and 1 is >= Px
        nog.add_edge(final[j,0],final[j,1], origshortpath=final[j,2])
        iter+=1
print(iter)
#            print(iter)


NameError: name 'final' is not defined

In [ ]:


pos=nx.get_node_attributes(nog,'pos')
nx.draw(nog,pos,hold=None,node_size=10)
plt.show()


pos=nx.get_node_attributes(fcg,'pos')
nx.draw(fcg,pos,hold=None,node_size=10)
plt.show()